### ISSUE TITLE
Compile Yad as portable windows version

### ISSUE THREAD

**Issue by deajan** [maravento/winzenity#1]
Hello,

I stumbled upon your winzenity page, and tried the single executable under windows which works great.
I would like to use yad, so I can use forms with default texts.
Do you have any build instructions for your current zenity executable, so I can try to build yad from it ?

Best regards.

**Comment by deajan** [comment]
I digged a long way to compile yad for windows, but some symbols aren't present on windows (the fork function if I remember), so I abandonned this, in favor of a python UI.
Thanks for your answer anyway :)

**Comment by maravento** [comment]
Thanks to you for your visit. We regret that we could not help you anymore

**Comment by GribanovIvan** [comment]
> I digged a long way to compile yad for windows, but some symbols aren't present on windows (the fork function if I remember), so I abandonned this, in favor of a python UI.
> Thanks for your answer anyway :)

compilled yad for windows? where i can get it?
