### ISSUE TITLE
Problem with --list

### ISSUE THREAD

**Issue by izderadicka** [maravento/winzenity#2]
I have problem with --list option

This is my working test case on linux:
```
echo -n -e "a\nb\n" | zenity --list --title=testik --column A
```

In windows I tried similar (in powershell):
```
 echo "a`nb`n" | .\local\bin\zenity.exe --list --column A  --title testik
```

It works if I double click on line,  but if I just select line and then click OK button dialog hangs and becomes inresponsive ( but selection is printed to stdout before).

And I actually want to use it in WSL, where it does not work at all:
```
echo -n -e "a\nb\n" | /mnt/c/Users/izderadi/local/bin/zenity.exe --list --title=testik --column A
```

here dialogs hangs immediately (Not Responding) and no buttons ore columns are displayed.
(tried also windows end of line - same problem). 
Without piping input to stdin dialog works (but obviously is useless).

I'm trying on Windows 10.

**Comment by ZerooCool** [comment]
I don't , look the man page, and, i have add example for Linux ( only )

My site is non official.
https://wiki.visionduweb.fr/index.php?title=Programmation_GNU_Linux_Zenity

You can test if Zenitor_3 work with Windows ?

You can look the fork Yad.

**Comment by maravento** [comment]
Example in cmd:
`/path_to/zenity.exe --list  --title="My List" --column="Column A" --column="Column B" "A1" "B1" "A2" "B2"`
